project:
  type: website
  output-dir: docs

website:
  title: "Ethical Issues in Remote Sensing"
  navbar:
    right:
    
    - href: index.qmd
      text: Home
      
    - href: about.qmd
      text: Common Questions
      
    - href: tabs/ethics.qmd
      text: Ethical Issues
      
    - href: tabs/explore.qmd
      text: Explore
    
    - href: tabs/remotesensing.qmd
      text: Try it for Yourself!
      
    - href: tabs/Resources.qmd
      text: Resources
      
format:
  html:
    theme: styles.scss 
    toc: true
    page-layout: full
    mainfont: Nanum Myeongjo
  
editor: visual