project:
  type: website
  output-dir: docs

website:
  title: "Ethical Issues in Remote Sensing"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - href: about.qmd
        text: Common Questions
        
      - href: tabs/explore.qmd
        text: Explore
        
      - href: tabs/News.qmd
        text: News
        
      - href: tabs/remotesensing.qmd
        text: Try it for Yourself!

format:
  html:
    theme: styles.scss 
    toc: true
    page-layout: full
    mainfont: Nanum Myeongjo
  
editor: visual